### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by HenryCY** [shubhmsng/blurred-barcode-extraction#1]
When I run your code, it has the following issues. Which version of OpenCV do you use? Thanks

Traceback (most recent call last):
  File "/home/Barcode & QR-Code/bar-code/blurred-barcode-extraction-master/project.py", line 123, in oneDB
    self.barcode = linear.linear(self.FName)
  File "/home/Barcode & QR-Code/bar-code/blurred-barcode-extraction-master/linear.py", line 63, in linear
    contours, hierarchy = cv2.findContours(closed.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack

**Comment by shubhmsng** [comment]
opencv 3.0
